name: Generate SBOM

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  # schedule:
  #   # Run weekly on Sundays at 2 AM UTC
  #   - cron: '0 2 * * 0'

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '19'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install tools
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          npm install -g jsonlint
          
      - name: Generate and format SBOM
        run: |
          syft packages . -o syft-json=sbom-syft.json
          jsonlint -f sbom-syft.json > sbom-syft-formatted.json
          mv sbom-syft-formatted.json sbom-syft.json
          
      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-files
          path: sbom-*.json
          retention-days: 30
          
      - name: Display SBOM summary
        run: |
          echo "## SBOM Generation Summary" >> $GITHUB_STEP_SUMMARY
          echo "Generated SBOM: sbom-syft.json" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Package count:" >> $GITHUB_STEP_SUMMARY
          syft packages . -q | wc -l >> $GITHUB_STEP_SUMMARY